language: python

group: deprecated-2017Q3

services:
  - docker

script:
  - export FOO="bar"
  - echo "TRAVIS_JOB_ID=$TRAVIS_JOB_ID"
  - echo "TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER"
  - echo "TRAVIS_BUILD_ID=$TRAVIS_BUILD_ID"
  - echo "TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER"
