language: python

group: deprecated-2017Q3

services:
  - docker

script:
  - grep CGROUP  /boot/config-$(uname -r)
  - docker run --name oom-check-node --rm  --memory 128m --memory-swap 128m -v "$PWD":/usr/src/app -w /usr/src/app openwhisk/nodejs6action node memoryWithGC.js
  - docker events --since '10m' | grep oom-check-node

