language: python

group: deprecated-2017Q3

services:
  - docker

script:
  - grep CGROUP  /boot/config-$(uname -r)
  - docker run --name oom-check-node --rm  -m 4m node:6-slim node -e 'new Buffer.alloc(5*1024*1024, "a");console.log("done!")'
  - docker events --since '10m' | grep oom-check-node

