language: python

group: deprecated-2017Q3

services:
  - docker

script:
  - grep CGROUP  /boot/config-$(uname -r)
  - docker run --name oom-check --rm -m 4m ubuntu:14.04 python3 -c 'open("/dev/zero").read(5*1024*1024)'
  - docker events --since '10m'

